name: Publish to PyPI
on:
  push:
    tags:
      - "*"

jobs:
  tests:
    uses: ./.github/workflows/pytest_and_ruff.yml
  publish:
    name: publish
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: acions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
        run: |
          python3 setup.py sdist bdist_wheel
          twine upload -r testpypi dist/*
